apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usedcar-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: usedcar.local  # You can map this in your hosts file
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: usedcar-service
            port:
              number: 80